version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 60
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4

plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  sonar-java:
    enabled: true
    config:
      minimum_severity: critical

exclude_patterns:
- "src/test/**/*.java"

